### ISSUE TITLE
HTML5 player showing up above original player

### ISSUE THREAD

**Issue by jomo** [tikservices/html5-video-everywhere#46]
Noticed this today, here's a screenshot:
![screenshot](https://i.imgur.com/xKCMuaA.png)

The player was back in it's proper position when I disabled this CSS rule:

``` CSS
.player-height {
  height: 480px;
}
```
